### ISSUE TITLE
manage.py index_zaken crashes with a keyerror.

### ISSUE THREAD

**Issue by svenvandescheur** [GemeenteUtrecht/zaakafhandelcomponent#325]
manage.py index_zaken crashes with a keyerror.

```
docker-compose exec backend src/manage.py index_zaken   
Traceback (most recent call last):
  File "src/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/app/src/zac/elasticsearch/management/commands/index_zaken.py", line 24, in handle
    zaken = get_zaken_all()
  File "/app/src/zac/core/services.py", line 384, in get_zaken_all
    zaak.zaaktype = zaaktypen[zaak.zaaktype]
KeyError: 'https://openzaak.utrechtproeftuin.nl/catalogi/api/v1/zaaktypen/e84a5b45-ecc1-4777-a9aa-e8cae9511315'
```

**Comment by svenvandescheur** [comment]
Most likely caused by incorrect cache by running index_zaken earlier with an incomplete configuration.

**Comment by damm89** [comment]
Had the same problem. Steps below fixed it. (probably not all necessary)

1) sudo docker exec -it <your-redis-container> redis-cli FLUSHALL
2) sudo docker-compose up -d --force-recreate --build ingress-dev
3) sudo docker-compose exec backend src/manage.py index_zaken

**Comment by sergei-maertens** [comment]
the Redis flushing was sufficient for us last Friday - maybe that's a good one to add to the readme/documentation. I'm not sure we can prevent this. Perhaps the `index_zaken` command *could* check that fetching all zaaktypen returns results rather than an empty list, and if an empty list is seen, give a warning/command error and suggest to flush the cache?
